# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["gh-json-server"]
  pull_request:
    branches: ["gh-json-server"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          # update the Node version to meet your needs
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Build
        run: |
          npm ci
          # configure the build here
          npm install
          npm run build --if-present
          # npm run export
          # touch out/.nojekyll
      - name: Test
        run: |
          npm test
      - name: Deploy
        # configure an external GitHub Pages deploy workflow here
        # https://github.com/JamesIves/github-pages-deploy-action
        # https://github.com/nguyenquy0710/my-json-server
        uses: nguyenquy0710/my-json-server
        with:
          branch: gh-json-server
          folder: out
